name: tracktion
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  flutter_bloc: ^6.1.0
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2
  moor: ^3.4.0
  path_provider: ^1.6.24
  moor_flutter: ^3.1.0
  flutter_staggered_grid_view: ^0.3.3
  union: ^0.0.3+1
  font_awesome_flutter: ^8.11.0
  flutter_cupertino_date_picker:
    git: https://github.com/daveleenew/flutter-cupertino-date-picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^3.4.0
  build_runner: ^1.10.7

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/home.svg
    - assets/vectors/abs.svg
    - assets/vectors/back.svg
    - assets/vectors/butt.svg
    - assets/vectors/calfs.svg
    - assets/vectors/chest.svg
    - assets/vectors/hamstrings.svg
    - assets/vectors/legs.svg
    - assets/vectors/quads.svg
    - assets/vectors/shoulders.svg
    - assets/vectors/arms.svg

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
